<a href="https://colab.research.google.com/github/saransh-singh-228/Employee-Retention-Prediction/blob/main/classifier_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv("HR_Dataset.csv")
x= dataset.iloc[:,:].values
x= np.delete(x, -4, 1)
y= dataset.iloc[:, -4].values

In [ ]:
print(x[:10])

[[0.38 0.53 2 157 3 0 0 'sales' 'low']
 [0.8 0.86 5 262 6 0 0 'sales' 'medium']
 [0.11 0.88 7 272 4 0 0 'sales' 'medium']
 [0.72 0.87 5 223 5 0 0 'sales' 'low']
 [0.37 0.52 2 159 3 0 0 'sales' 'low']
 [0.41 0.5 2 153 3 0 0 'sales' 'low']
 [0.1 0.77 6 247 4 0 0 'sales' 'low']
 [0.92 0.85 5 259 5 0 0 'sales' 'low']
 [0.89 1.0 5 224 5 0 0 'sales' 'low']
 [0.42 0.53 2 142 3 0 0 'sales' 'low']]


In [ ]:
print(y[:10])

[1 1 1 1 1 1 1 1 1 1]


##Encoding Categorical Data

### Encoding the Independent Variable salary



In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [ ]:
print(x[:10])

[[0.0 1.0 0.0 0.38 0.53 2 157 3 0 0 'sales']
 [0.0 0.0 1.0 0.8 0.86 5 262 6 0 0 'sales']
 [0.0 0.0 1.0 0.11 0.88 7 272 4 0 0 'sales']
 [0.0 1.0 0.0 0.72 0.87 5 223 5 0 0 'sales']
 [0.0 1.0 0.0 0.37 0.52 2 159 3 0 0 'sales']
 [0.0 1.0 0.0 0.41 0.5 2 153 3 0 0 'sales']
 [0.0 1.0 0.0 0.1 0.77 6 247 4 0 0 'sales']
 [0.0 1.0 0.0 0.92 0.85 5 259 5 0 0 'sales']
 [0.0 1.0 0.0 0.89 1.0 5 224 5 0 0 'sales']
 [0.0 1.0 0.0 0.42 0.53 2 142 3 0 0 'sales']]


### Encoding the Independent Variable dept.



In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [ ]:
print(x[:10])

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.38 0.53 2 157 3 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.8 0.86 5 262 6 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.11 0.88 7 272 4 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.72 0.87 5 223 5 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.37 0.52 2 159 3 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.41 0.5 2 153 3 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.1 0.77 6 247 4 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.92 0.85 5 259 5 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.89 1.0 5 224 5 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.42 0.53 2 142 3 0
  0]]


In [ ]:
print(len(x[1]))

20


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)


In [ ]:
print(x_train[:5])

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.68 0.7 4 185 4 0
  0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.45 0.47 2 135 3 0
  0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.7 0.99 5 135 4 0
  0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.58 0.58 3 122 3 0
  0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.97 0.58 4 187 4 1
  0]]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train[:,15:18]=sc.fit_transform(x_train[:,15:18])
x_test[:,15:18]=sc.transform(x_test[:,15:18])


In [ ]:
print(x_train[:10])

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.68 0.7
  0.16799976073064457 -0.32167138865940104 0.3458098019997247 0 0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.45 0.47
  -1.4543979286110091 -1.3244864767427889 -0.33935727432040336 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.7 0.99
  0.9791986054014714 -1.3244864767427889 0.3458098019997247 0 0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.58 0.58
  -0.6431990839401823 -1.5852183996444698 -0.33935727432040336 0 0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.97 0.58
  0.16799976073064457 -0.2815587851360655 0.3458098019997247 1 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.89 0.56
  0.16799976073064457 0.48058068180730934 0.3458098019997247 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.45 0.46
  -1.4543979286110091 -1.4648805890744632 -0.33935727432040336 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.69 0.73
  0.16799976073064457 

In [ ]:
print(x_test[:10])

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.67 0.39
  -1.4543979286110091 0.11956725009728968 2.401311030960109 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.51 0.98
  0.16799976073064457 0.8817067170406645 -0.33935727432040336 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.66 0.54
  -1.4543979286110091 -1.3044301749811211 -1.0245243506405315 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.53 0.81
  -0.6431990839401823 1.4833957698906972 -1.0245243506405315 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.83 0.98
  0.16799976073064457 1.1624949417040131 1.0309768783198527 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.4 0.41
  -0.6431990839401823 0.6209747941389836 -0.33935727432040336 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.45 0.57
  -1.4543979286110091 -1.1640360626494468 -0.33935727432040336 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.76 0.99
  0.9791986054014714 1.0

## Training the classification model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acs=accuracy_score(y_test, y_pred)
print(acs)

[[2279    8]
 [  24  689]]
0.9893333333333333
